### ISSUE TITLE
Try Q&A plug-in

### ISSUE THREAD

**Issue by nschonni** [gctools-hackathon-ircc/gcconnex#1]
https://elgg.org/plugins/2472722

https://github.com/ColdTrick/questions

- [x] create a PR to GCConnex that just adds our 1.12 compatible fork to the `mod` folder
- [x] create an PR to add our translations to the ColdTrick repo

Composer version will be handled by the other work we have done

**Comment by TouficS** [comment]
use v2.1.2 for Elgg/GCConnex 1.12 compatiblity

**Comment by duboisp** [comment]
Before we need to `composer update tedivm/stash` before

**Comment by duboisp** [comment]
Merged upstream
* https://github.com/ColdTrick/questions/pull/12
* https://github.com/ColdTrick/questions/pull/11

Question plugins for elgg version 112 https://github.com/gctools-hackathon-ircc/questions/tree/elgg_112_gcconnex

PR to gcconnex upstream: https://github.com/gctools-outilsgc/gcconnex/pull/962
