### ISSUE TITLE
Split GCConnex to plug-in repositories

### ISSUE THREAD

**Issue by nschonni** [gctools-hackathon-ircc/gcconnex#3]

**Comment by nschonni** [comment]
Related to https://github.com/gctools-outilsgc/gcconnex/issues/426

**Comment by nschonni** [comment]
http://www.gcpedia.gc.ca/wiki/GCconnex_Development/List_of_Plugins

**Comment by chown-your-poptarts** [comment]
Mike
- [x] b_extended_profile
- [x] gc_api
- [x] gc_group_deletion
- [x] GC_profileStrength
- [x] GoC_dev_banner
- [x] ideas
- [x] missions
- [x] missions_organization
- [x] missions_profile_extend
- [x] toggle_language
- [x] unvalidated_user_cleanup
- [x] wet4

Ebenezer
- [x] achievement_badges
- [x] cp_notifications
- [x] custom_error_page
- [x] c_email_extensions
- [x] c_members_byDepartment
- [x] c_module_dump
- [ ] ~c_notification_messages~
- [x] gcforums
- [x] gcProfilePictureBadges
- [x] gcRegistration 
- [x] widget_manager_accessibility

**Comment by nschonni** [comment]
I've created the listed empty projects for the unchecked ones. I'm going to circle back now and check out the mods @smellems did when he did his split

**Comment by chown-your-poptarts** [comment]
[composer.zip](https://github.com/gctools-hackathon-ircc/gcconnex/files/905640/composer.zip)

Take a look at this for the root composer for gcconex.

**Comment by nschonni** [comment]
I've kicked of the conversion in https://github.com/nschonni/gcconnex/tree/composer, so let me know when everything is done.
1. Add composer.json to the repo
- Verify license in the manifest
```json
{
    "name": "gctools-hackathon-ircc/GC_profileStrength",
    "type": "elgg-plugin",
    "require": {
        "composer/installers": ">=1.0.8"
    },
    "license": "CC-BY-3.0"
}
```
Some may be `GPL-2.0` instead of `CC-BY-3.0`
- use the "Create new file" on the Code page, and call it `composer.json`
- Click the button to create a branch and pull request, and call the branch `composer`

1. Replace the module in gccconnex
- Add the github repository to the composer.json
- ~Delete the plug-in from the mod folder `rf -rf mod/PLUGIN`~
- composer require gctools-hackathon-ircc/PLUGIN:dev-composer
- Verify the diff is now only the composer.json again
- Re-delete the plug-in from mod folder
- Create commit "Moving PLUGIN to composer"

**Comment by chown-your-poptarts** [comment]
Extracted GC Connex plugins in GC Collab
- [x] b_extended_profile
- [x] gc_api
- [x] gc_group_deletion
- [x] GC_profileStrength
- [x] GoC_dev_banner
- [x] ideas
- [x] missions
- [x] missions_organization
- [x] missions_profile_extend
- [x] toggle_language
- [x] unvalidated_user_cleanup
- [x] wet4
- [x] achievement_badges
- [x] cp_notifications
- [x] custom_error_page
- [x] c_email_extensions
- [x] c_members_byDepartment
- [x] c_module_dump
- [x] ~c_notification_messages~
- [x] gcforums
- [x] gcProfilePicturesBadges
- [x] gcRegistration 
- [ ] widget_manager_accessibility

Not GC Collab extracted

**Comment by nschonni** [comment]
See https://github.com/nschonni/gcconnex/tree/composer/mod for more plug-ins that need to be removed

**Comment by chown-your-poptarts** [comment]
GC plugins we missed.

**Mike**
- [x] gc_fedsearch_gsa
- [x] gc_group_layout
- [x] gc_newsfeed
- [x] gc_official_groups
- [x] gc_onboard

**Ebenezer**
- [x] gc_splash_page
- [x] gc_streaming_content
- [x] gccollab_stats
- [x] geds_sync

**Comment by nschonni** [comment]
PR created https://github.com/gctools-outilsgc/gcconnex/pull/956
