### ISSUE TITLE
Add French Translations to Q&A plugin

### ISSUE THREAD

**Issue by nschonni** [gctools-hackathon-ircc/gcconnex#7]
1. Copy the en.php from elgg_112_gcconnex branch to fr.php https://github.com/gctools-hackathon-ircc/questions/blob/elgg_112_gcconnex/languages/en.php
1. Replace the right hand strings in the file
1. Create a pull request to the elgg_112_gcconnex branch
1. Update the composer reference in our demo site

**Comment by nschonni** [comment]
I've sent a link to the fr.php placeholder to Erica

**Comment by nschonni** [comment]
Erica provides the translations along with some typo fixes. Toufic will move them across to the fr.php and en.php in the questions repo

**Comment by duboisp** [comment]
I just remarked that we have translated the language file for the version 5 of the plugin and not for the version 2.1.2.

Files to help the comparaison:
* [Language file for Version 2.1.2](https://github.com/ColdTrick/questions/blob/da3a847e2bf89a37102de3c5c223f616721b1234/languages/en.php)
* [French translated language file for version 5.0](https://github.com/gctools-hackathon-ircc/questions/blob/b0aa57ea08ffceb9133a4b816f08f375cb169418/languages/fr.php) 

Then
* [ ] Compare our translated file for version 5 and match it for version 2.1.2
* [ ] Finish plugin submission with nschonni English typo fix (submited in pr upstream 12)

**Comment by duboisp** [comment]
Finally the version 5 of the language file is compatible with version 1.2.1.
